apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meu-site
  labels:
    app: locust
  name: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
        - image: linuxtips/locust-giropops:1.0
          name: locust
          env:
            - name: LOCUST_LOCUSTFILE
              value: "/usr/src/app/scripts/locustfile.py"
            - name: LOCUST_HOST
              value: "http://meu-site:80"
          ports:
            - containerPort: 8089
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "100m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
          volumeMounts:
            - name: locust-scripts
              mountPath: /usr/src/app/scripts
      volumes:
        - name: locust-scripts
          configMap:
            name: locust-scripts
            optional: true
