apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: meu-site
  name: meu-site
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kube-site.henriqzimer.com.br
    secretName: wildcard-henriqzimer-tls
  rules:
  - host: kube-site.henriqzimer.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: meu-site
            port:
              number: 3000
