apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: meu-site
  name: meu-site
spec:
  ingressClassName: nginx
  rules:
    - host: meu-site-k8s.henriqzimer.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meu-site
                port:
                  number: 3000
