apiVersion: v1
kind: Service
metadata:
  namespace: meu-site
  name: meu-site
  labels:
    app: meu-site
spec:
  selector:
    app: meu-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP
